### ISSUE TITLE
"null" op causes error

### ISSUE THREAD

**Issue by poppuyo** [opspec-io/opctl#131]
```
jason@arondight:~/scribbles/opdocs$ sudo opctl run happy-birthday-op
OpStarted Id='4ee9c7e87d264448653c6aacdcc6b6f7' OpRef='/home/jason/scribbles/opdocs/.opspec/happy-birthday-op' Timestamp='2017-03-06T01:24:49Z'

Event channel closed unexpectedly
```

Here was the op in question:
```yaml
name: happy-birthday-op
description: this is an op that wishes a happy birthday
inputs:
  name:
    string:
  age:
    number:
```
